---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: openebs-hostpath
