---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: openebs-hostpath
