apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:nw9VMbpgsxDFUmULBFCEuqpQLLvNuk6v6Xd1gtGdCKRWivPO,iv:iC9KtG5DNJh0Sb7fp6L6gD/Hk9KhLg+TCxir5bi6QQw=,tag:WA1tjSXAyAuCD0KfkMQkvQ==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:f7SH8LCPX0Rsv7MD5GYXgzu+4Q8NaT2hXJN2uEOohKMiPmmJaD32fcLbvUpaEsUdUX6cqr5aEKE/hcf0mKKRos5XncLfSi4R1wGLm9lC34SqTHkJNGs0zYICohxrxtoh9oF+VCO53Gz0MOlDObObG1rCR+PZsgdJ8Mq8DDG+fMs+HRdMa6YlrvAt7H5wVkTdcC/GPyKHbxOMcCfnQPqWVZ558/Pgt87Dl4uQSVE4HQ==,iv:HJgF/Ls1q84tB1d02/qVutTvPZI4cv4mN/8SiPJQ0/Y=,tag:1hHl2umcA5jkO0y7EaOeBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSFZOTDZDVUxsOTdTSFJx
            OEVEMkY1d1R0UDBHMnBVZWhsUC9EaGM3c2pFCjIyaHVnS0wvZ3NQaEJ0N3FEVzVi
            ZEt1cE5tU1JHNUdQdW52cUtmQlhFVEEKLS0tIHJUUlJ4ejdnSWVZdDZ1RHFPcHZ6
            KzRTQzNZQjBKUVp1eEZWblNIbTR2U2sKcO54EPX5Geb4cwdvmQD0xp5f3IZY5CfG
            jZEmfh8BJofWRX4mgqPJvltBsDjc0RUwc683BvVWs1x7pyL+0PRngw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T20:21:52Z"
    mac: ENC[AES256_GCM,data:9LAj5KCigUuTE62KYwEn9OiWuFE750RIANnFUcBUZbGeqDGftxpzBmgmSQSBZLzHAyv0GzH31LhjWF7NHSHgK7XE+xPgG44Pp3WYNEdNLckQ9FxmzwS+IfHiefyG3+C+ZAsgZR6Un09EX5kEm9A804yovROOzqQ6VV3SgQR+lJs=,iv:gaNz+ZCSBEEkgXbJUhWBltqbB1C4eXVszQnWtOATnE0=,tag:73OjYBtv1JRTOJCBLh6AUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
