apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5bM+OP72o2SoiZcB7sBg1hmIi/TRhaMJc+Es0GhOLLjibIR6npETUA==,iv:3R+2J+9sYN8b4XN+Oxley59JZSuQOovu97X6Gyh5z08=,tag:ygpSRULbP2CiehCIrxeskQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cjFOQnE3MTgzVGltSDhH
            UkhOVkxEcW1QWWNnelA2M1BpckZGSUtmZ0FvCnVoWE5pbjRDZWkvaFV2akpUVVhi
            Uko0YTFwbGt5WEpKR2FyVTEzYlVxaDgKLS0tIGM4V3Z5UU9vRUExWTZEVTkzU2J3
            Z3dLSWpGVTVNVGJISkxXdzNDQkE2WFkKkiRGtWWJ9f4cuNkjmyABaInXBwmR3Z90
            fjpQyDBPW5ESnXR0WW3nT1Q/3pOXIpX1vmyG7OdCca10BcvEQ+Yn1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T12:48:31Z"
    mac: ENC[AES256_GCM,data:Bc5+wLwUoD5NmnFlrxH9R7LUWHp9PcC2Uys4E8yxyfsaU+DsC6M1g6W5x5IzX53ZYroto5ihXa1GwqqEl9qxfABD0zXXl5iN07M9Wx38n8nifOO+jDtnagJYjqh367QmtGPRB3CFXb8OYtp0DciMoYTOVysGAlc9QtfKJmPi35g=,iv:gaeYC+I+xsvpaPGndvMLCsdH5hVqW1FaUcRmZl1VFgY=,tag:BLwNQem2JlnhBMKdRr+m9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
