apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2rWv/dP/4mDYygUF1u3ETKBTEGSwPPtvLyp66O/RaAmb/UTdccPunw==,iv:nWLsBmsM/bjlDq5XRg4wvwmcPEeqfX0wO6cxbGkusRY=,tag:r7KnY/jgoKOtrrrBjzizqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISW1DbG1ESEFMT1g4cWM1
            RFJCSXRqYmQ5VnNZK0JTM0hqbjhMeFQ2S2lFCllDbGRIQi8vNVpkQnk0WEdQcjds
            VGtjUWNLazRnK1NvelhiRHpPWUkrQmcKLS0tIEpEZVdaM29EMDF0aGF0MXRPaExh
            bDR4TzlvSzdpOE1tZ2w5dGVEVEhyRWMKTE8F/Z9olHtH098G8J37Sr23AA1B+AcQ
            Pbr/VcsSM6gWra6F2D/yYjRpMZAj//O2vdTMHfIEfXXYMIOjYHH2LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T23:05:45Z"
    mac: ENC[AES256_GCM,data:3hhNF4KZTbNApQEuvjx39iAxcUAl15FeYp786MdDMtUi/5ADGFUIg+maVO9Bsn1V9yuoWa2+GNk5b02d+hvTV2D5/8Sv4EVDFfPlgpyY7jfNRW4h6r006Ixv+toI2VOd5KPfR9ZTY3r0K1XN5t2agCi3qLfudt0Bj/Lay/uUJa0=,iv:17fJ602w6A8PpeDcOtWGOZVf9aBpbHqNmsx6LdYKOYE=,tag:RgoK/tE6aD39TxRrWVfqsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
