---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-storage-claim
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Mi
  storageClassName: openebs-hostpath
