---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wg-easy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      wg-easy:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/wg-easy/wg-easy
              tag: 12
            # Specify external hostname and port as environment variables
            env:
              WG_HOST: "${SECRET_DNS}"
              WG_PORT: "30000"
              WG_DEFAULT_DNS: "192.168.0.4, 192.168.0.5"
              PASSWORD: "${SECRET_WG_EASY_PASSWORD}"
              UI_TRAFFIC_STATS: true
              PROMETHEUS_ENABLED: true
            ports:
              - containerPort: 51820
                name: wg
                protocol: UDP
              - containerPort: &port 51821
                name: http
                protocol: TCP
            # Give pod permissions to modify iptables and load the wireguard kernel module
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
                  - SYS_MODULE
            # Persistent storage location
            # volumeMounts:
            #   - mountPath: /etc/wireguard
            #     name: config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    # path: /admin
                    port: 51821
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
    service:
      app:
        controller: wg-easy
        ports:
          http:
            port: *port
            protocol: TCP
          wg:
            port: 51820
            protocol: UDP
    serviceMonitor:
      app:
        serviceName: wg-easy
        endpoints:
          - port: http
            interval: 1m
            scrapeTimeout: 10s
          - port: wg
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
