---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wg-easy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      wg-easy:
        strategy: RollingUpdate
        containers:
          - name: wg-easy
            # Specify external hostname and port as environment variables
            env:
              - name: WG_HOST
                value: "${SECRET_DNS}"
              - name: WG_PORT
                value: "30000"
              - name: WG_DEFAULT_DNS
                value: "192.168.0.4, 192.168.0.5"
              - name: PASSWORD
                value: "${SECRET_WG_EASY_PASSWORD}"
              - name: UI_TRAFFIC_STATS
                value: true
              - name: PROMETHEUS_ENABLED
                value: true
            image: ghcr.io/wg-easy/wg-easy
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 51820
                name: wg
                protocol: UDP
              - containerPort: &port 51821
                name: http
                protocol: TCP
            # Use the http server for pod health checks
            livenessProbe:
              failureThreshold: 3
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: http
              timeoutSeconds: 1
            readinessProbe:
              failureThreshold: 3
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: http
              timeoutSeconds: 1
            startupProbe:
              failureThreshold: 30
              periodSeconds: 5
              successThreshold: 1
              tcpSocket:
                port: http
              timeoutSeconds: 1
            # Give pod permissions to modify iptables and load the wireguard kernel module
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
                  - SYS_MODULE
            # Persistent storage location
            volumeMounts:
              - mountPath: /etc/wireguard
                name: config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    # path: /admin
                    port: 51821
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
    service:
      app:
        controller: wg-easy
        ports:
          wg:
            port: 51820
            protocol: UDP
          http:
            port: *port
            protocol: TCP
    serviceMonitor:
      app:
        serviceName: wg-easy
        endpoints:
          - port: http
            interval: 1m
            scrapeTimeout: 10s
          - port: wg
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
