---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wg-easy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      wg-easy:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/wg-easy/wg-easy
              tag: 12
            env:
              WG_HOST: "${SECRET_DDNS}"
              WG_PORT: 3000
              WG_DEFAULT_DNS: 192.168.0.4, 192.168.0.5
              PASSWORD: "${SECRET_WG_EASY_PASSWORD}"
              UI_TRAFFIC_STATS: true
              PROMETHEUS_ENABLED: true
            ports:
              - containerPort: 51820
                name: wg
                protocol: UDP
              - containerPort: &port 51821
                name: http
                protocol: TCP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /admin
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                add:
                  - NET_ADMIN
                  - SYS_MODULE
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
    service:
      app:
        controller: wg-easy
        ports:
          wg:
            port: 51820
            protocol: UDP
          http:
            port: *port
            protocol: TCP
    serviceMonitor:
      app:
        serviceName: wg-easy
        endpoints:
          - port: http
            interval: 1m
            scrapeTimeout: 10s
          - port: wg
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
