apiVersion: v1
kind: Secret
metadata:
    name: wg-easy-secrets
stringData:
    WG_HOST: ENC[AES256_GCM,data:QXcfHIlX0eTDHBJIJZ3WApPCgA==,iv:nBkQMb83lVcqvftbWOHk063MteSO0hS+4s4Q65cVtAE=,tag:FKCsLTIVRpUMAQnICmknKw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:b1xOWmpUcO6KHpkdV5tQPtwRqGh16Oc9dKS2tsOUfh8=,iv:DLVcG35xxJu3d55DHOs9OUyjuCdRlG4kZYRpuRfhSUc=,tag:l2TUti0TGnIVcAlGrLLBqg==,type:str]
    WG_PORT: ENC[AES256_GCM,data:la1fYk8=,iv:AKck6lV5umpNHcXFScj9yj1tlf5teaNDry0jlNNHFNU=,tag:tgvgbZl2m8BROCItULIdqw==,type:str]
    WG_DEFAULT_DNS: ENC[AES256_GCM,data:CaO2u6hQL12YOfaR7cTPSgDlpR4hBPw/,iv:fqmZtm/Hr/qw8iGsRxdKDNs3+IwZpqRuqawbQP3d7LY=,tag:CDSLul+MYNONMJxRrASY/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeGk4cituc3RlRDJqVWlm
            L1NyVE5kNlJITFExS1U5ZzRURGVXVkJLU2lvCmFjY2F2bnFGZGFuZWtOaFJYU2I0
            ODI1US8zWmM4NS90ZWdqSE1mLzhpanMKLS0tIGE3YUdUZGVzL1ovUC9KN3h4bVFW
            Zmg2d0NHbjIvbEgxU2hhRy91S2ttcVEKasV/8AJ4vXXZ1An6LS6xr5SC/v66cN46
            TAys4j5a3pQwBotpeXQi4Fxol7+wScV9f5SUmk7PjYGeSJHzbZgNYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T19:44:55Z"
    mac: ENC[AES256_GCM,data:TyngiOWgMNvabRQXL+zc5HylsAvDNAlxoHc5Bo2mivAWVcnGJNkM0zLV+f40jFEGN33xMQldrUonqIwWP5lA9n+p5e9890O6dW0BT8M3NRAqxFF3+/tH3tc5YUTN9YGxtEmmoUlAwpfikTQujiT3DKyY06XPD2W+PFLdU1CE+mU=,iv:RckMofl1IzcNWNO+oXYuZzcriKa+KFIm1LCHnK7AoCc=,tag:KRfAICTERXPoXW4WQ+9lWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
