apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:A2RMa2AoGSAoWPbWf/VJDLW6M9stcAd+0hIPVIamO2ON9A16HjfXsLaIXijw2LeCRDKy9kRu3ESshrw6YSHLc+eiKfNl5ZJSQpNOl6QaN/YizEOgGO0RQDRgmJVg6g==,iv:YbFarH0pNole+/GJGM2rLI03K6i2n2OWoWoMyHXqcaI=,tag:JnE35oLEKgx2bdZaLGvbGA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ymxzra83XtGhs3g=,iv:mk/fIidmgW5SJFjkgx43Tfh0jFUnyZweEjICY2aJnxo=,tag:erRCdvIU2BTyMINFalM9Xw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:njgfbLQigZa9N7SnhYsohc1yYCOz3SwyM9Od11codg==,iv:lPyWPtSGgVjpIW82+CSOKgGsFEnIr5Vx2geAZRatuWk=,tag:6R+ZqFoOMypU5K1r7Dlwzw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VN7J4zJVNMOBUX2klJAd/ulrtaln/S0yFtLMu88/tb0qtw6e,iv:LVQUQiYSBCQgd+VjSitvsMqHDF9QkftdRJdbxK2iwYY=,tag:Avon/e4I0XayjG9iHMGVbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TXA3bGJVZUwrSHdsK3h4
            aWxIL2dEbU02STVMMHJFRWhKS1VWR2FocFc4CjEybFYzSnEzM0FCelFXRlBOR1Zw
            TERXSUJnVllpcWZubWE3MEhmTzVZa0UKLS0tIFU2bC9hWnhsOFdmYWFBaFhiRDJr
            SWdoTU94SXgzdVAralR4RFRieDRzdVEKKBf+Fz3S0itkLp44BqZA4S300TcYvBut
            DkGnJTF22kALSMBHi59uQp6ehtAR0nMWdb15QOO9OkuKfC5yqlMcUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T12:48:31Z"
    mac: ENC[AES256_GCM,data:YzFlLbDAFJM9RJbT5jYocsHM1ROwXYI70q/6Yxoeiv5MoFQ637UzMieNJGOAtfa+cYOPpUdyCZ9fiKcg+L+O0w/yUehZdIR+J4bGVddWrYeM6/zZXH4mUXBuYbkW4FBFald7ZWgs824qQAT0jCJXCA4gZlBgZtE8g59Kyp7ub00=,iv:c3nNbvpJZbWQGWrtV2D7yVcSqsBwu1OnEnEINDCDyCA=,tag:u/OzZuxRDKl/OFvlJqTE+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
