apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:BIkCBapWNPHLn7LJzeJOe8bwpIDPM44XOkNqATdeWUs=,iv:t4U0bI+ZWf1XLJRatKFFMleNmXS9eV6W8DDMGeq9aHA=,tag:SnLowVw9TPhMToMTTTfIuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcDdyVXFnYWQyQVA5N1ls
            YkJ5TXRReUxqeXcvWkJuekNLRTVtbkMrUkc0CkluNi94b0Y3bis0dHRXVSsvOGph
            NXNoTEdSZHh6M0VEMTU2UForenh2NE0KLS0tICtwR21sTzBHQlVNWjZjRTdiWnJs
            bW9IeEFrdXBLMVpFSnJTRUZlY0d6bHMKeUM0MrMdJ5XHpi2LVJ1Ujax3a/DONwf6
            z8NLNHPhEqFljyvg51ArllqyqgSVHSeArt1UnGK7rAWKBg6EIBP/fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T23:05:45Z"
    mac: ENC[AES256_GCM,data:jR7rvOD0gd5BUpTYziffg07FGTBNCjdC5wjzfKlSz6giG1jqBVjOFCA02o/JYiq1MigOIArXjEv77Z99nfIHVExrCvyNlmFCZ+bYk1fLlx3FhWz/WHwN+NfJcsEAu/vy1IC4nkimR04Y8zs/KP0aWPwQbLQLj7tvFtIPojXZFd8=,iv:EUCDjV+9RE/6CQfTTrz87g/5u30uu/+ZAU1uL+6v3PI=,tag:DsTUj5FSabvZ421vsbn5+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
