apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:svVw14LxmP3sSOxkAzGldvE26UlyltqdT06zpCso+wI=,iv:0VjNgVXsbgIMmE/1U9Jh0Y8v6IInp+Vyziw2yG5FqyQ=,tag:eJQKhZ+JbzBsQ5vszqgJQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3c3BPSGJaL3AwaFo3WEhS
            N2p4aWF3bnJtQ1lPZit3K3RxdUNWQjI2dWdnCmN3T2krblJWRVA1RGNNZzNlb2xL
            T0QrcTh6Zm1WRkVKb0UwWCtXYlJDL1EKLS0tIEZUbjY1Z0o4cjcxWHpTWHRJZDVU
            Y1hFeStrbW9IMDN4RDNpVU82SlpLUVUKnKrflYewjlErpftBwUbOk9gn7fZ5LDRM
            ABez1K7vE/3TyOF30H4PZ2MNae8gA5BQK+cnjyCpCpIbSZBH1YmEjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T06:40:52Z"
    mac: ENC[AES256_GCM,data:mKAPjPEtaXpjlhnu0et+Xi2YIOoNvh1IHHbfQLgdYIVBiNyUE1cSRdliGYAG2Z89sSNRqllPQz4ZlxGqYf+exRA2EFGXc8i4R/meI3mGhMa4p2vI47adkdQch1kUrMFb4X65tLXxFjYc366fLlGHzdOyS1slcnG36zru+PhcS6E=,iv:0ROoK2QQeIPzMGaoHIrPgZNWZlszO3cmdD3RFRC1dZ4=,tag:OYBteHE/gq1mefO0LqpR0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
