apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:14JvDa1qSbT0ipTZ+wCN/IbByv34gWzlinscSUYm7K8=,iv:1dHVkKKgtHuF4J97dLAsDJYJLgDEJNIvd9CD6MhLC/g=,tag:+B07EmugfLHhh6OuDycmvQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:V1uqTGF8cLT0/cxAEFEr+X864FKOiOLP19spZx/19vfyw6Fs,iv:JkQEZ8ct6v5OY4dCe+HwdkSE/8dvKugyyUAzcNlg82w=,tag:JHfQk4bVdvCKCTHWjHzFPQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:rSxVKT3LvadnEeKUfbErDyxIlCCFMKPE+SO19Irw0I5jt7nKPF84ig==,iv:lHzpj8eRkcZmi6txY6UbNp/AdlWXuc5iDboaLipQmG0=,tag:vSqnVFqW/Jmx7UpNinE6BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTEs0QzlsVk1YRDdxRnZx
            dGdRZkdNYUtBMUZQei9lMm1PR09UWDExUVhVCkFvdEI1bTBVdW1yL3BUcGcxNXA4
            dXNjT2tBejlwUGJ6MjR1bW01ZmllSWMKLS0tIHg0b0dXUXZpVDRXRHllOVFUS0U2
            QkZkTGJZOXRiWFp5eWtRNVA4ODN6aTQKsoV7pqAC1jEA3j2pmUm+J1s2ooJyBUgy
            CGPrg29jZN/eqMPcmA3IMyp5Rcqa/zzxJL3YvnBxUfkNL19j+mt3dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-06T22:25:02Z"
    mac: ENC[AES256_GCM,data:Wpfunjp+JBf5bniGHHQ5VHjH4y7GePC+l2b+cDvdo+5wF+yfRHEXPY9bP7BjHADkR3JDDJeKefMzdRXbr6giYJF2+v2aY1IbrCQ6kl25o7kRwqPFAfL9XbokVxsWtA92cHV7ON/iN/QuzoLXCaDJsazo3eBKhtnC2qgbRV9zpzg=,iv:Wm9n3l8Skftm/prt3aNVT1GH56BJIRlB7Gw9keN33c0=,tag:RbEjEoqN8vw58+VuNC1UqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
