apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:VnyKh8FOGGx5fng8zFBwBdkrG8SNi3ivLOLx0cvkzM1ROlwTf7l/jw==,iv:AuJAKJAsUGDSz0M2puh/Mrea8Z0B1/ddzIwEfejFiVc=,tag:vCIbJvmBVukk1+nnbYky2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWStrelNVc2sybE1DU0dh
            YWZneHpTdU9VU2tPcmIxaXpIZnJoK2hKNWw4Ci9WclUvdUhlZG1FQkZnWlF3bS8x
            NStGMXpjMFB3MXhIazI4Vi9BT1AxNGMKLS0tIFU1V2NZN2lhZ3ByZVNzck0wTldl
            d1ZJSlJTN0xDbkhyaTZua2JNdjVjc2sKXsZ289DaJus5tSF2nrGZrwGmnXriCbdJ
            RfOBH69bukGhB6Gf6oz1nhSGusmJ4XegElU/UxdEreQVpyaTncT7og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T18:56:37Z"
    mac: ENC[AES256_GCM,data:C2zYjYf21+jIYJMvP5OuOUEtBZjIvCTp2siAdwTrXgMBRiXOlx53vtT64ANyl2F9Q9IAeuxoiryEWfkNZLxGeBHLDzzf2YFn1M6ma5oKd3G1K71dZj8O9oqSA4tu4hssoK1whONq67FEb3kg4yYz9CzeZ5h2+VydjuUkiCuWJO0=,iv:9j3oNLg5A0XZKLEBNHCg9VBkdiQV5rye+MN/Fi3K8D4=,tag:b0QciFOMWsJd+OG54j4KOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
