apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:0z+9s7AJgihwMG9wlwYG4IXvBXMiT+/bc8oplMH1JFC684OpcxppXg==,iv:HFxHE/C1CNktt4Nh2fbfR2Tji3yYb5PMKVDKLmu/C/Q=,tag:PuzlKl+3eaSo70vWaOBdcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0wvp5rvmzzeumqyhm42rchx2z4lmx9d0t6r007ku2qtgzv6t43q0w8xtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNVQxZWFTSHZ5VnowUVQ4
            bWV4dURlOXFvcW5VTDAvMDhkamZWTXJ1OGhBClRQN1YxWEliRGRRb2ttRnBLeHd6
            SU8rRW50eEpROUQyUUlqVUhXTFpiSzQKLS0tIHg4SnR3cXhuTDU4bW11Ym9MR3Jj
            ZHdQZ1RBSUtTZ0lGM0UzZ0RkQlFjWE0K0UQqXPteKUD5DzlPBvDBld/UNekcPaRC
            daz/HtD0RSBxz6zILoEYxt9kAInqZKk0BY+RHpsnww9zjjvCINhl2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T12:48:31Z"
    mac: ENC[AES256_GCM,data:lJf+7rYbbyRQyi0vvahkGWpgUW1b/ULby6Dvit5MQNVj85wMACwlAj8DyA6aMnYjjxnx3xUS+xXfC6wibNdhRcidJk8v6/tYjEQ/ZDJIgmqj57FcPDbGC/PiB0cAo9dCO9L7J/hss3kC2/F39ofPJSagZfWhYS/ksweV+Ikuosk=,iv:BaHBr3OYwLa92jhUr3gD69LSqB92sb1RFrgJW6Qjdxs=,tag:bkvAbDHKQJzwO+57gNczZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
